In [1]:
from mpi4py import MPI
from manapy.ast import Variable
from manapy.base.base import Struct
from manapy.ddm import Domain
from manapy.partitions import MeshPartition
from manapy.solvers.advec.tools_utils import initialisation_gaussian_2d
import numpy as np
import time
from numba import cuda

import matplotlib.pyplot as plt

from timeit import default_timer as timer
from manapy.cuda.utils import VarClass
###############
# test_time
###############

def test_time(iter, fun):
  #fun()
  start_time = timer()
  for _ in range(iter):
    fun()
  end_time = timer()
  elapsed_time = (end_time - start_time) / iter
  print(f"{elapsed_time * 1000:.5f} ms")
  #print(f"{elapsed_time * 1000000:.5f} micros")

###############
# init
###############
def init(dim, mesh_path):
  running_conf = Struct(backend="numba", signature=True, cache=True, float_precision="single")
  MeshPartition(mesh_path, dim=dim, conf=running_conf, periodic=[0,0,0])

  running_conf = Struct(backend="numba", signature=True, cache =True, float_precision="single")
  domain = Domain(dim=dim, conf=running_conf)
  ne = Variable(domain=domain)
  u  = Variable(domain=domain)
  v  = Variable(domain=domain)
  w  = Variable(domain=domain)
  
  P = Variable(domain=domain)
  Pinit = 2.0
  cells = domain.cells
  initialisation_gaussian_2d(ne.cell, u.cell, v.cell, P.cell, cells.center, Pinit)

  u.face[:] = 2.
  v.face[:] = 0.
  w.face[:] = 0.
  
  u.interpolate_facetocell()
  v.interpolate_facetocell()
  w.interpolate_facetocell()
  return (domain, ne, u, v, w, P)

In [2]:
dim = 3
mesh_file = "/home/aben-ham/Desktop/work/stage/manapy/mesh/3D/cube.msh"
domain, ne, u, v, w, P = init(dim=dim, mesh_path=mesh_file)

Reading gmsh file ...
Saving partition files ...
Number of Cells: 4573
Number of Vertices: 1140
Local domain contruction ...
---------------------------------
---------------------------------
set att: BCdirichlet
set att: BCneumann
set att: BCneumannNH
set att: cell
set att: dirichletfaces
set att: face
set att: ghost
set att: gradcellx
set att: gradcelly
set att: gradcellz
set att: gradfacex
set att: gradfacey
set att: gradfacez
set att: gradhalocellx
set att: gradhalocelly
set att: gradhalocellz
set att: halo
set att: haloghost
set att: halotosend
set att: neumannNHfaces
set att: neumannfaces
set att: node
set att: psi
set att: psihalo
compile kernel_facetocell to cuda => signature=void(float32[:], float32[:], int32[:,:], int32)
compile kernel_celltoface to cuda => signature=void(float32[:], float32[:], float32[:], float32[:], int32[:,:], int32[:], int32[:], int32[:], int32[:])
compile kernel_define_halosend to cuda => signature=void(float32[:], float32[:], int32[:])
compile kernel_

In [3]:
#PETScKrylovSolver
from manapy.solvers.ls import PETScKrylovSolver

# put this code to PETScKrylovSolver init function so bypass the import of petsc4py
"""
    # try_imports(['import petsc4py',],
    #             'cannot import petsc4py solver!')
    
    # from petsc4py import PETSc as petsc
    
    #self.petsc = petsc
    self.ksp   = None
    
    self.converged_reasons = {}                                                                                                                                                                             
    # for key, val in six.iteritems(petsc.KSP.ConvergedReason.__dict__):                                                                                                                                 
    #     if isinstance(val, int):                                                                                                                                                                       
    #         self.converged_reasons[val] = key    
"""

conf = Struct(reuse_mtx=True, scheme='diamond', verbose=False, precision="single")
L = PETScKrylovSolver(domain=domain, var=P, conf=conf)

SetUp the Linear system ...


In [4]:
# args list
#? The order is imported of the argument list

VarClass.convert_to_var_class([
    domain.nodes,
    domain.faces,
    domain.cells,
    domain.halos,
    ne,
    domain,
    ne.domain._cells,
    L,
    L.var
])

args = [
  L.domain.faces.cellid,
  L.domain.faces.nodeid,
  L.domain.nodes.oldname,
  L.domain.cells.volume,
  L.domain.nodes.ghostcenter,
  L.domain.cells.loctoglob,
  L.domain.faces.param1,
  L.domain.faces.param2,
  L.domain.faces.param3,
  L.domain.faces.param4,
  L.domain.Pbordnode,
  L.domain.Pbordface,
  L.rhs0,
  L.var.BCdirichlet,
  L.domain.faces.ghostcenter,
  L.matrixinnerfaces,
  L.domain.halofaces,
  L.var.dirichletfaces,
]



---------------------------------
---------------------------------
can't get attr _nbnodes => _nbnodes
can't get attr nbnodes => _nbnodes
can't set attr for R_x => can't set attribute
can't set attr for R_y => can't set attribute
can't set attr for R_z => can't set attribute
set att: _R_x
set att: _R_y
set att: _R_z
set att: _cellid
set att: _ghostcenter
set att: _ghostfaceinfo
set att: _ghostid
set att: _haloghostcenter
set att: _haloghostfaceinfo
set att: _haloghostid
set att: _halonid
set att: _lambda_x
set att: _lambda_y
set att: _lambda_z
set att: _loctoglob
set att: _name
set att: _number
set att: _oldname
set att: _periodicid
set att: _vertex
can't set attr for cellid => can't set attribute
can't set attr for ghostcenter => can't set attribute
can't set attr for ghostfaceinfo => can't set attribute
can't set attr for ghostid => can't set attribute
can't set attr for haloghostcenter => can't set attribute
can't set attr for haloghostfaceinfo => can't set attribute
can't set attr

In [9]:
L.rhs0

VarClass([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [5]:
from manapy.ast.functions3d import get_rhs_loc_3d as cpu_function
from manapy.cuda.manapy.ast.cuda_functions3d import get_kernel_get_rhs_loc_3d as gpu_function

numba_fun = domain.backend.compile(cpu_function, echo=True, signature=True)
cuda_fun = gpu_function()
#cuda_fun = get_kernel_get_triplet_3d()

compile get_rhs_loc_3d to cpu => signature=(int32[:,:], int32[:,:], int32[:], float32[:], float32[:,:,:], int32[:], float32[:], float32[:], float32[:], float32[:], float32[:], float32[:], float32[:], int32[:], float32[:,:], int32[:], int32[:], int32[:])
compile device_search_element to cuda => signature=int32(int32[:], int32)
compile kernel_get_rhs_loc_3d to cuda => signature=void(int32[:,:], int32[:,:], int32[:], float32[:], float32[:,:,:], int32[:], float32[:], float32[:], float32[:], float32[:], float32[:], float32[:], float32[:], int32[:], float32[:,:], int32[:], int32[:], int32[:])
compile kernel_assign to cuda => signature=void(float32[:], float32)


In [6]:
numba_fun(*args)
%timeit numba_fun(*args)

314 µs ± 7.09 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
cuda_fun(*args)
%timeit cuda_fun(*args)

CUDADispatcher(<function get_kernel_get_rhs_loc_3d.<locals>.kernel_get_rhs_loc_3d at 0x70d7d3fed9d0>) is called
1 => VarClass<int32, (9874, 2)>
2 => VarClass<int32, (9874, 4)>
3 => VarClass<int32, (1140,)>
4 => VarClass<float32, (4573,)>
5 => VarClass<float32, (1140, 7, 6)>
6 => VarClass<int32, (4573,)>
7 => VarClass<float32, (9874,)>
8 => VarClass<float32, (9874,)>
9 => VarClass<float32, (9874,)>
10 => VarClass<float32, (9874,)>
11 => VarClass<float32, (1140,)>
12 => VarClass<float32, (9874,)>
13 => VarClass<float32, (4573,)>
14 => VarClass<int32, (0,)>
15 => VarClass<float32, (9874, 4)>
16 => VarClass<int32, (8418,)>
17 => VarClass<int32, (0,)>
18 => VarClass<int32, (0,)>


/home/aben-ham/anaconda3/envs/stage/lib/python3.8/site-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/home/aben-ham/anaconda3/envs/stage/lib/python3.8/site-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 32 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


787 µs ± 17.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
# verify

def verify(a, decimal, plot):
  b = VarClass.to_device(a)
  if plot == True:
    plt.plot(a, label="cpu")
    plt.plot(b, label="gpu")
    plt.legend()
    plt.show()
  np.testing.assert_almost_equal(a, b, decimal=decimal)


for i, arg in enumerate(args):
  print(f"{i + 1} => test arg {arg}")
  verify(arg, decimal=2, plot=False)


1 => test arg [[4197   -1]
 [4243   -1]
 [4215   -1]
 ...
 [1361 2321]
 [1342 1361]
 [2321 3600]]
2 => test arg [[ 116   40   39    3]
 [ 117   49   48    3]
 [ 118   76   75    3]
 ...
 [1139  830 1083    3]
 [1139  920 1083    3]
 [1139 1024 1083    3]]
3 => test arg [2 2 2 ... 0 0 0]
4 => test arg [3.9885298e-04 5.7941291e-04 4.5172661e-04 ... 2.5228161e-04 7.1672039e-05
 8.3594947e-05]
5 => test arg [[[ 9.3839747e-01  1.0183012e+00  9.8169875e-01  4.3560000e+03
    3.0000000e+00  5.0000000e+02]
  [ 9.8169875e-01  1.0183012e+00  9.3839753e-01  4.3530000e+03
    3.0000000e+00  5.0100000e+02]
  [ 1.0183012e+00  9.3839747e-01  9.8169875e-01  4.3300000e+03
    2.0000000e+00  1.1570000e+03]
  ...
  [ 9.3839747e-01  9.8169875e-01  1.0183012e+00  4.3560000e+03
    5.0000000e+00  1.5320000e+03]
  [ 9.8169875e-01  9.3839747e-01  1.0183012e+00  4.3300000e+03
    5.0000000e+00  1.5330000e+03]
  [-1.0000000e+00 -1.0000000e+00 -1.0000000e+00 -1.0000000e+00
   -1.0000000e+00 -1.0000000e+00]]

 [[