## RECT

In [3]:
import subprocess
import os
import numpy as np
import sys

sys.path.append(os.path.join(os.getcwd()))
from helpers.DomainTables import DomainTables
from helpers.TablesTestRect2D import TablesTestRect2D

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float64'
dim=2
mesh_name = 'rectangles.msh'

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'helpers', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=9, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 1
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 5
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 6
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 8
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 3
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 4
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 7
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/rectangles.msh precision float64 dim 2 rank 0
Reading gmsh file ...
path /medi

In [4]:
import importlib

module = importlib.import_module("helpers.TablesTestRect2D")
importlib.reload(module)
TestTablesRect2D = getattr(module, "TablesTestRect2D")

module = importlib.import_module("helpers.Checker2D")
importlib.reload(module)
Checker2D = getattr(module, "Checker2D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TestTablesRect2D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = Checker2D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()



# ============================== #
# ========== Summary =========== #
# ============================== #
===> 33 [P] 1 [F] Total 34
---------------------------------------------------------
---------------------------------------------------------
### Entities Details
[P] 1/34: Cell Vertices
[P] 2/34: Cell Center
[P] 3/34: Cell Area
[P] 4/34: Cell Neighbors by face
[P] 5/34: Cell Neighbors by node
[P] 6/34: Cell Halo by face
[P] 7/34: Cell Halo by node
[P] 8/34: Cell Ghostnid *
[P] 9/34: Cell Haloghostnid and Haloghostcenter *
[P] 10/34: Cell Number of cells
[P] 11/34: Face Vertices
[P] 12/34: Face Measure
[P] 13/34: Face Center
[P] 14/34: Face Name
[P] 15/34: Face Oldname
[P] 16/34: Face Normal(Only abs)
[P] 17/34: Face CellId
[P] 18/34: Face Ghostcenter
[P] 19/34: Face Cell face normal
[P] 20/34: Face Number of faces
[P] 21/34: Node Cellid
[P] 22/34: Node Loctoglob
[P] 23/34: Node Halonid
[P] 24/34: Node Oldname
[P] 25/34: Node Name
[P] 26/34: Node ghostid, ghostcenter and ghostface

False

In [9]:
a = domain_tables.d_halo_sizehaloghost
a = np.array(a)

b = test_tables.halo_sizehaloghost
print(b)
print(a)

[3 2 2 2 2 2 4 4 4]
[4 2 2 2 2 2 4 4 4]


## Triangles

In [1]:
import subprocess
import os
import numpy as np
import sys

sys.path.append(os.path.join(os.getcwd()))
from helpers.DomainTables import DomainTables
from helpers.TablesTestRect2D import TablesTestRect2D

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float64'
dim=2
mesh_name = 'triangles.msh'

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'helpers', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=7, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 2
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 4
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 3
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 0
Reading gmsh file ...
Mesh partitionning ...
Saving partition files ...
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 1
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 5
Number of Cells: 200
Number of Vertices: 121
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/triangles.msh precision float64 dim 2 rank 6
Local domain contruction ...
saving mesh do

In [2]:
import importlib

module = importlib.import_module("helpers.TablesTestTriangles2D")
importlib.reload(module)
TestTablesTriangles2D = getattr(module, "TablesTestTriangles2D")

module = importlib.import_module("helpers.Checker2D")
importlib.reload(module)
Checker2D = getattr(module, "Checker2D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TestTablesTriangles2D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = Checker2D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()


# ============================== #
# ========== Summary =========== #
# ============================== #
===> 34 [P] 0 [F] Total 34
---------------------------------------------------------
---------------------------------------------------------
### Entities Details
[P] 1/34: Cell Vertices
[P] 2/34: Cell Center
[P] 3/34: Cell Area
[P] 4/34: Cell Neighbors by face
[P] 5/34: Cell Neighbors by node
[P] 6/34: Cell Halo by face
[P] 7/34: Cell Halo by node
[P] 8/34: Cell Ghostnid *
[P] 9/34: Cell Haloghostnid and Haloghostcenter *
[P] 10/34: Cell Number of cells
[P] 11/34: Face Vertices
[P] 12/34: Face Measure
[P] 13/34: Face Center
[P] 14/34: Face Name
[P] 15/34: Face Oldname
[P] 16/34: Face Normal(Only abs)
[P] 17/34: Face CellId
[P] 18/34: Face Ghostcenter
[P] 19/34: Face Cell face normal
[P] 20/34: Face Number of faces
[P] 21/34: Node Cellid
[P] 22/34: Node Loctoglob
[P] 23/34: Node Halonid
[P] 24/34: Node Oldname
[P] 25/34: Node Name
[P] 26/34: Node ghostid, ghostcenter and ghostface

True

## Gamma in different domain

In [38]:
domain_tables_7 = DomainTables(nb_partitions=7, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
domain_tables_5 = DomainTables(nb_partitions=5, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

def glob_to_loc(domain):
  loctoglob = domain.d_cell_loctoglob
  dic = {}
  for p in range(len(loctoglob)):
    for i in range(len(loctoglob[p])):
      g_index = loctoglob[p][i]
      dic[g_index] = (p, i)
  return dic

dic7 = glob_to_loc(domain_tables)
dic5 = glob_to_loc(domain_tables_5)

def get_cell_faces_vertices(partitionId, cellId, domain):
  c_faces = domain.d_cell_faces[partitionId][cellId]
  c_faces = c_faces[0:c_faces[-1]]

  c_faces_nodes = domain.d_faces[partitionId][c_faces]
  c_faces_nodes = c_faces_nodes[:, 0:2]

  node_vertices = domain.d_nodes[partitionId][c_faces_nodes][:, :, 0:2]
  return node_vertices

a = get_cell_faces_vertices(partitionId=5, cellId=0, domain=domain_tables) # domain split into 7 part
b = get_cell_faces_vertices(partitionId=3, cellId=9, domain=domain_tables_5) # domain split into 5 part
# (5, 0) and (3, 9) refer to the same cell
np.testing.assert_array_almost_equal(a, b) # they have different face nodes arrangement
# cell_7 = [[p1, p2], [p1, p2], [p1, p2]]
# cell_5 = [[p2, p1], [p1, p2], [p1, p2]]

for i in range(200):
  print(i, dic7[i], dic5[i])
  a = get_cell_faces_vertices(partitionId=5, cellId=0, domain=domain_tables)
  b = get_cell_faces_vertices(partitionId=3, cellId=9, domain=domain_tables_5)
  np.testing.assert_array_almost_equal(a, b)

AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 4 / 12 (33.3%)
Max absolute difference: 1.
Max relative difference: 1.
 x: array([[[1. , 2. ],
        [0. , 2.5]],
...
 y: array([[[0. , 2.5],
        [1. , 2. ]],
...

# 3D

In [5]:
import subprocess
import os
import numpy as np
import sys

sys.path.append(os.path.join(os.getcwd()))
from helpers.DomainTables import DomainTables
from helpers.TablesTestRect2D import TablesTestRect2D

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float32'
dim=3
mesh_name = 'cuboid.msh'

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'helpers', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=4, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/cuboid.msh precision float32 dim 3 rank 3
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/cuboid.msh precision float32 dim 3 rank 2
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/cuboid.msh precision float32 dim 3 rank 1
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/cuboid.msh precision float32 dim 3 rank 0
Reading gmsh file ...
Mesh partitionning ...
Saving partition files ...
Number of Cells: 1000
Number of Vertices: 1331
Local domain contruction ...
saving mesh domain_meshes4PROC/mesh1.hdf5
saving mesh domain_meshes4PROC/mesh2.hdf5
saving mesh domain_meshes4PROC/mesh3.hdf5
saving mesh domain_meshes4PROC/mesh0.hdf5
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/2D/mesh/cuboid.msh precision float32 dim 3 rank 0
Reading gmsh file ...
Saving partition files ...
Number of Cells: 1000
Number of Vertices: 1331
Loc

In [11]:
print(domain_tables.d_cells[0][[0, 1, 2, 3, 4, 5]])

[[ 0  1  2  3  4  5  6  7  8]
 [ 4  5  6  7  8  9 10 11  8]
 [ 8  9 10 11 12 13 14 15  8]
 [12 13 14 15 16 17 18 19  8]
 [16 17 18 19 20 21 22 23  8]
 [20 21 22 23 24 25 26 27  8]]
