In [ ]:
import subprocess
import os
import sys

sys.path.append(os.path.join(os.getcwd()))
sys.path.append(os.path.join(os.getcwd(), 'domain'))
from tests.domain.primary.domain.local_domain_1cpu_testing import DomainTables

mesh_list = [
  (2, 'rectangles.msh'),
  (2, 'triangles.msh'),
  (3, 'cube.msh'),
  (3, 'tetrahedron.msh'),
  (3, 'tetrahedron_big.msh'),
]

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float32'
dim, mesh_name = mesh_list[0]

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'domain', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=4, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

In [1]:
import os
import sys
sys.path.append(os.path.join(os.getcwd()))
sys.path.append(os.path.join(os.getcwd(), 'domain'))
from domain.local_domain_1cpu_testing import LocalDomain1Cpu, SingleCoreDomainTables

mesh_list = [
  (2, 'rectangles.msh'),
  (2, 'triangles.msh'),
  (3, 'cube.msh'),
  (3, 'tetrahedron.msh'),
  (3, 'tetrahedron_big.msh'),
]
float_precision = 'float32' # the test does not support float64 or int64 yet
root_file = os.getcwd()
dim, mesh_path = mesh_list[3] # also modify dim variable accordingly
mesh_path = os.path.join(root_file, 'mesh', mesh_path) #tests/domain/primary/mesh

def create_domain(nb_parts):
  mesh = Mesh(mesh_path, dim)
  partitioning = Partitioning(mesh, float_precision)
  local_domain_data = partitioning.create_sub_domains(nb_parts=nb_parts)

  local_domains = LocalDomain1Cpu.create_local_domains(local_domain_data)
  domains = [Domain(local_domains[i]) for i in range(len(local_domains))]

  return domains, SingleCoreDomainTables(domains, float_precision)

l_domains, domain_tables = create_domain(1)
g_domains, unified_domain = create_domain(1)

[Rank 0]: bounds Time 0.000334 seconds (delta: 0.000333 seconds)
[Rank 0]: node_cellid Time 0.063230 seconds (delta: 0.061963 seconds)
[Rank 0]: cell_cellnid Time 2.717202 seconds (delta: 2.652569 seconds)
[Rank 0]: _create_info Time 4.290711 seconds (delta: 1.572760 seconds)
[Rank 0]: Create cell volume and center Time 4.349502 seconds (delta: 0.058114 seconds)
[Rank 0]: Face measure face center face normal Time 4.768109 seconds (delta: 0.417929 seconds)
[Rank 0]: cell_halonid, face_haloid, node_haloid Time 4.768880 seconds (delta: 0.000066 seconds)
[Rank 0]: Create face and node names Time 4.858090 seconds (delta: 0.088991 seconds)
[Rank 0]: create_bf_cellid Time 4.900251 seconds (delta: 0.041565 seconds)
[Rank 0]: Create shared_ghost_info Time 4.915675 seconds (delta: 0.014628 seconds)
[Rank 0]: Create shared_ghost_info Time 5.112811 seconds (delta: 0.196286 seconds)
[Rank 0]: _create_halo_ghost_tables Time 5.113628 seconds (delta: 0.000093 seconds)
[Rank 0]: face_gradient_info Time

In [ ]:
#Tetra
import importlib

module = importlib.import_module("helpers.TablesTestTetra3D")
importlib.reload(module)
TablesTestTetra3D = getattr(module, "TablesTestTetra3D")

module = importlib.import_module("helpers.TetraChecker3D")
importlib.reload(module)
TetraChecker3D = getattr(module, "TetraChecker3D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TablesTestTetra3D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = TetraChecker3D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_node_info()
checker.test_face_info()
checker.test_halo_info()
checker.summary()


In [ ]:
# Triangle
import importlib

module = importlib.import_module("helpers.TablesTestTriangles2D")
importlib.reload(module)
TestTablesTriangles2D = getattr(module, "TablesTestTriangles2D")

module = importlib.import_module("helpers.Checker2D")
importlib.reload(module)
Checker2D = getattr(module, "Checker2D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TestTablesTriangles2D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = Checker2D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()

In [2]:
# Rectangle
import importlib

module = importlib.import_module("helpers.TablesTestRect2D")
importlib.reload(module)
TestTablesRect2D = getattr(module, "TablesTestRect2D")

module = importlib.import_module("helpers.Checker2D")
importlib.reload(module)
Checker2D = getattr(module, "Checker2D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TestTablesRect2D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = Checker2D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()



# ============================== #
# ========== Summary =========== #
# ============================== #
===> 34 [P] 0 [F] Total 34
---------------------------------------------------------
---------------------------------------------------------
### Entities Details
[P] 1/34: Cell Vertices
[P] 2/34: Cell Center
[P] 3/34: Cell Area
[P] 4/34: Cell Neighbors by face
[P] 5/34: Cell Neighbors by node
[P] 6/34: Cell Halo by face
[P] 7/34: Cell Halo by node
[P] 8/34: Cell Ghostnid *
[P] 9/34: Cell Haloghostnid and Haloghostcenter *
[P] 10/34: Cell Number of cells
[P] 11/34: Face Vertices
[P] 12/34: Face Measure
[P] 13/34: Face Center
[P] 14/34: Face Name
[P] 15/34: Face Oldname
[P] 16/34: Face Normal(Only abs)
[P] 17/34: Face CellId
[P] 18/34: Face Ghostcenter
[P] 19/34: Face Cell face normal
[P] 20/34: Face Number of faces
[P] 21/34: Node Cellid
[P] 22/34: Node Loctoglob
[P] 23/34: Node Halonid
[P] 24/34: Node Oldname
[P] 25/34: Node Name
[P] 26/34: Node ghostid, ghostcenter and ghostface

True

In [4]:
# Cube
import importlib

module = importlib.import_module("helpers.TablesTestHexa3D")
importlib.reload(module)
TestTablesRect2D = getattr(module, "TablesTestHexa3D")

module = importlib.import_module("helpers.Checker3D")
importlib.reload(module)
Checker3D = getattr(module, "Checker3D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TestTablesRect2D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = Checker3D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()



# ============================== #
# ========== Summary =========== #
# ============================== #
===> 33 [P] 0 [F] Total 33
---------------------------------------------------------
---------------------------------------------------------
### Entities Details
[P] 1/33: Cell Vertices
[P] 2/33: Cell Center
[P] 3/33: Cell Area
[P] 4/33: Cell Neighbors by face
[P] 5/33: Cell Neighbors by node
[P] 6/33: Cell Halo by face
[P] 7/33: Cell Halo by node
[P] 8/33: Cell Ghostnid *
[P] 9/33: Cell Haloghostnid and Haloghostcenter *
[P] 10/33: Cell Number of cells
[P] 11/33: Face Vertices
[P] 12/33: Face Measure
[P] 13/33: Face Center
[P] 14/33: Face Name
[P] 15/33: Face Oldname
[P] 16/33: Face Normal(Only abs)
[P] 17/33: Face CellId
[P] 18/33: Face Ghostcenter
[P] 19/33: Face Number of faces
[P] 20/33: Node Cellid
[P] 21/33: Node Loctoglob
[P] 22/33: Node Halonid
[P] 23/33: Node Oldname
[P] 24/33: Node Name
[P] 25/33: Node ghostid, ghostcenter and ghostfaceinfo *
[P] 26/33: Node haloghosti

True

In [ ]:

import numpy as np

def compile(func):
  # return func
  return numba.jit(nopython=True, fastmath=True, cache=True)(func)


def reinterpret_int32_as_float32(i):
    return np.int32(i).view(np.float32)

def reinterpret_int32_as_float64(i):
    return np.int64(i).view(np.float64)

def reinterpret_float32_as_int32(i):
    return np.float32(i).view(np.int32)

def reinterpret_float64_as_int32(i):
    return np.int32(np.float64(i).view(np.int64))

def reinterpret(i, type_id):
  if type_id == 0:
    z = np.int32(i).view(np.float32)
  else:
    z = np.int64(i).view(np.float64)

  return z

def test(arr, i):
  arr[0] = reinterpret_int32_as_float32(i)
  arr[1] = reinterpret_float32_as_int32(arr[0])

reinterpret_int32_as_float32= compile(reinterpret_int32_as_float32)
reinterpret_float32_as_int32= compile(reinterpret_float32_as_int32)
reinterpret_int32_as_float64= compile(reinterpret_int32_as_float64)
reinterpret_float64_as_int32= compile(reinterpret_float64_as_int32)
reinterpret = compile(reinterpret)
test = compile(test)

a = np.array([0, 1], dtype=np.float64)

test(a, 233)
print(a)


In [ ]:
import numba
from numba.typed import Dict, List
from numba import types

def compile(func):
  # return func
  return numba.jit(nopython=True, fastmath=True, cache=True)(func)

int_type = types.int32
map_halo_int = Dict.empty(key_type=int_type, value_type=types.ListType(int_type))

def test(dic):
  if 1 not in dic:
    dic[np.int32(1)] = List.empty_list(int_type)
    dic[np.int32(1)].append(10)
    dic[np.int32(1)][-1] = 22

    dic[np.int32(2)] = List.empty_list(int_type)
    dic[np.int32(2)].append(10)
    dic[np.int32(2)][-1] = 33

  for i in dic:
    print(dic[i])

test = compile(test)

test(map_halo_int)
map_halo_int

In [ ]:
import os
import sys
sys.path.append(os.path.join(os.getcwd()))
sys.path.append(os.path.join(os.getcwd(), 'domain'))
from domain.create_domain import Domain, Mesh, SingleCoreDomainTables, Partitioning


mesh_list = [
  (2, 'rectangles.msh'),
  (2, 'triangles.msh'),
  (3, 'cube.msh'),
  (3, 'tetrahedron.msh'),
  (3, 'tetrahedron_big.msh'),
]
float_precision = 'float32' # the test does not support float64 or int64 yet
root_file = os.getcwd()
dim, mesh_path = mesh_list[0] # also modify dim variable accordingly
mesh_path = os.path.join(root_file, 'mesh', mesh_path) #tests/domain/primary/mesh


mesh = Mesh(mesh_path, dim)
partitioning = Partitioning(mesh, float_precision)
partitioning.make_n_part(nb_parts=4)



In [9]:

from numba.typed import List
import numpy as np
from numba.typed import Dict, List
from manapy.backends.compile_fun import compile


def fun(a: 'int32[:, :]', out: 'int[:, :]'):
  s = a[out[0]]
  for i in range(s[-1]):
    s[i] += 1

fun = compile(fun)
a = np.zeros((3, 3), dtype=np.int32)
b = np.zeros((3, 3), dtype=np.int32)
a[:, -1] = 2
b[0] = 1
fun(a, b)
print(a)

=> fun -> (Array(int32, 2, 'A', False, aligned=True), Array(int32, 1, 'A', False, aligned=True))
[[0 0 2]
 [1 1 2]
 [0 0 2]]


In [6]:
from numba import int32, float64
from numba.typed import List
import numpy as np
from numba.typed import Dict, List
from manapy.backends.compile_fun import compile
from domain.LocalDomainStructData import LocalDomainStructData, LocalDomainStructDataType, ListLocalDomainStructDataType


def test(r: 'float64', a: LocalDomainStructDataType):
  a.nodes[0] = r



test = compile(test)

k = LocalDomainStructData()
k.nodes = np.zeros((12, 20), dtype=np.float64)
list_local_domains = List.empty_list(LocalDomainStructDataType)
list_local_domains.append(k)
#
test(0.2, k)
print(k.nodes[0])

=> test -> (float64, instance.jitclass.LocalDomainStructData#7dad8c20bfd0<nodes:array(float64, 2d, A),cells:array(int32, 2d, A),cells_type:array(int8, 1d, A),phy_faces:array(int32, 2d, A),phy_faces_name:array(int32, 1d, A),cell_loctoglob:array(int32, 1d, A),node_loctoglob:array(int32, 1d, A),node_oldname:array(int32, 1d, A),halo_neighsub:array(int32, 2d, A),node_halos:array(int32, 1d, A),node_halophyid:array(int32, 2d, A),halo_halosext:array(int32, 2d, A),halo_halosint:array(int32, 1d, A),halo_centvol:array(float64, 2d, A),phyid_recv:array(int32, 1d, A),phyid_recv_part_size:array(int32, 1d, A),phyid_send:array(int32, 1d, A),max_cell_nodeid:int32,max_cell_faceid:int32,max_face_nodeid:int32,max_node_haloid:int32,max_cell_halonid:int32,float_precision:int32,dim:int32,max_node_halophyid:int32,max_phy_face_nodeid:int32,nb_node_halos:int32,map_cells:DictType[int32,int32]<iv=None>,map_phy_faces:DictType[int32,int32]<iv=None>,map_nodes:DictType[int32,int32]<iv=None>,map_halos:DictType[int32,in