In [3]:
import subprocess
import os
import numpy as np
import sys

sys.path.append(os.path.join(os.getcwd()))
sys.path.append(os.path.join(os.getcwd(), 'domain'))
from tests.domain.primary.domain.create_domain import DomainTables

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float32'
dim=3
mesh_name = 'tetrahedron.msh'

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'domain', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=4, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

path /home/aben-ham/Desktop/work/manapy/tests/domain/primary/mesh/tetrahedron.msh precision float32 dim 3 rank 0
====> Start <=====
====> Creating Mesh <=====
gmsh:physical => triangle
gmsh:physical => tetra
node_cellid
Execution time: 0.006198 seconds
cell_cellnid
Execution time: 0.011579 seconds
cell_cellfid and boundary_faces
path /home/aben-ham/Desktop/work/manapy/tests/domain/primary/mesh/tetrahedron.msh precision float32 dim 3 rank 2
Execution time: 0.019076 seconds
node_bfid
Execution time: 0.019405 seconds
Start creating sub domains
Parse Input 
Start Creating SubDomains 
Make n part
Start dense to csr
Nb_vertices = 6000
size = 22800
End dense to csr
End METIS_PartGraphKway
End function
Create local cells
Create Physical faces
Create local domains struct
Create local domains struct p=0
Create map_bf_recv, shared_bf_recv
Create Tables
End Create Tables
Cells, CellsType, CellsLocToGlob
PhyFaces, PhyFacesName
Halo neighsub, Halos
End Halo neighsub, Halos
Create local domains struc

In [5]:
print(domain_tables.d_cell_faces[0])

[[   0    1    2    3    4]
 [   3    4    5    6    4]
 [   1    7    8    9    4]
 ...
 [3254 3255 3201 3256    4]
 [3256 3257 3001 3258    4]
 [3257 3209 3008 3259    4]]
