## Hexa

In [5]:
import subprocess
import os
import numpy as np
import sys

sys.path.append(os.path.join(os.getcwd()))
from tests.domain.primary.helpers.DomainTables import DomainTables

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float32'
dim=3
mesh_name = 'cube.msh'

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'helpers', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=4, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/mesh/cube.msh precision float32 dim 3 rank 0
Reading gmsh file ...

path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/mesh/cube.msh precision float32 dim 3 rank 2
Mesh partitionning ...
Saving partition files ...
Number of Cells: 1000
Number of Vertices: 1331
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/mesh/cube.msh precision float32 dim 3 rank 1
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/primary/mesh/cube.msh precision float32 dim 3 rank 3
Local domain contruction ...
Start ...
Start ...
Start ...
Start ...
Execution time: 0.066393 seconds
Execution time: 0.069468 seconds
Execution time: 0.080262 seconds
Execution time: 0.090248 seconds
saving mesh domain_meshes4PROC/mesh0.hdf5
saving mesh domain_meshes4PROC/mesh2.hdf5
saving mesh domain_meshes4PROC/mesh3.hdf5
saving mesh domain_meshes4PROC/mesh1.hdf5
path /media/aben-ham/SSD/aben-ham/work/manapy/tests/domain/prim

In [2]:
import importlib

module = importlib.import_module("helpers.TablesTestHexa3D")
importlib.reload(module)
TestTablesRect2D = getattr(module, "TablesTestHexa3D")

module = importlib.import_module("helpers.Checker3D")
importlib.reload(module)
Checker2D = getattr(module, "Checker3D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TestTablesRect2D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = Checker2D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()



# ============================== #
# ========== Summary =========== #
# ============================== #
===> 27 [P] 0 [F] Total 27
---------------------------------------------------------
---------------------------------------------------------
### Entities Details
[P] 1/27: Cell Vertices
[P] 2/27: Cell Center
[P] 3/27: Cell Area
[P] 4/27: Cell Neighbors by face
[P] 5/27: Cell Neighbors by node
[P] 6/27: Cell Halo by face
[P] 7/27: Cell Halo by node
[P] 8/27: Cell Ghostnid *
[P] 9/27: Cell Haloghostnid and Haloghostcenter *
[P] 10/27: Cell Number of cells
[P] 11/27: Face Vertices
[P] 12/27: Face Measure
[P] 13/27: Face Center
[P] 14/27: Face Name
[P] 15/27: Face Oldname
[P] 16/27: Face Normal(Only abs)
[P] 17/27: Face CellId
[P] 18/27: Face Ghostcenter
[P] 19/27: Face Number of faces
[P] 20/27: Node Cellid
[P] 21/27: Node Loctoglob
[P] 22/27: Node Halonid
[P] 23/27: Node Oldname
[P] 24/27: Node Name
[P] 25/27: Node ghostid, ghostcenter and ghostfaceinfo *
[P] 26/27: Node haloghosti

True

## Tetra

In [2]:
import subprocess
import os
import numpy as np
import sys

sys.path.append(os.path.join(os.getcwd()))
from tests.domain.primary.helpers.DomainTables import DomainTables

mpi_exec = "/usr/bin/mpirun"
python_exec = "/home/aben-ham/anaconda3/envs/work/bin/python3"
float_precision = 'float32'
dim=3
mesh_name = 'tetrahedron.msh'

def create_partitions(nb_partitions, mesh_name, float_precision, dim):
  root_file = os.getcwd()
  mesh_file_path = os.path.join(root_file, 'mesh', mesh_name)
  script_path = os.path.join(root_file, 'helpers', 'create_partitions_mpi_worker.py')
  cmd = [mpi_exec, "-n", str(nb_partitions), "--oversubscribe", python_exec, script_path, mesh_file_path, float_precision, str(dim)]

  result = subprocess.run(cmd, env=os.environ.copy(), stderr=subprocess.PIPE)
  if result.returncode != 0:
    print(result.__str__(), os.getcwd())
    raise SystemExit(result.returncode)

domain_tables = DomainTables(nb_partitions=4, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)
unified_domain = DomainTables(nb_partitions=1, mesh_name=mesh_name, float_precision=float_precision, dim=dim, create_par_fun=create_partitions)

path /home/aben-ham/Desktop/work/manapy/tests/domain/primary/mesh/tetrahedron.msh precision float32 dim 3 rank 1
path /home/aben-ham/Desktop/work/manapy/tests/domain/primary/mesh/tetrahedron.msh precision float32 dim 3 rank 0
Reading gmsh file ...
Mesh partitionning ...
Elapsed time: 0.042 s
path /home/aben-ham/Desktop/work/manapy/tests/domain/primary/mesh/tetrahedron.msh precision float32 dim 3 rank 2
path /home/aben-ham/Desktop/work/manapy/tests/domain/primary/mesh/tetrahedron.msh precision float32 dim 3 rank 3
Elapsed time: 0.296 s
Saving partition files ...
Number of Cells: 6000
Number of Vertices: 1331
Local domain contruction ...
Start ...
Start ...
Start ...
Start ...
_compute_cells_info`: 2.961428 seconds
_make_neighbors: 2.980105 seconds
_define_eltypes: 2.980431 seconds
_compute_cells_info`: 3.143463 seconds
_make_neighbors: 3.167970 seconds
_define_eltypes: 3.168635 seconds
_compute_cells_info`: 3.370816 seconds
_compute_cells_info`: 3.376226 seconds
_make_neighbors: 3.39617

In [14]:
a = domain_tables.d_halo_sizehaloghost[2]

print(a, type(a), domain_tables.d_cell_haloghostcenter[2].shape[0])

145 <class 'numpy.ndarray'> 145


In [1]:
import importlib

module = importlib.import_module("helpers.TablesTestTetra3D")
importlib.reload(module)
TablesTestTetra3D = getattr(module, "TablesTestTetra3D")

module = importlib.import_module("helpers.TetraChecker3D")
importlib.reload(module)
TetraChecker3D = getattr(module, "TetraChecker3D")

d_cell_loctoglob = domain_tables.d_cell_loctoglob
g_cell_nodeid = unified_domain.d_cell_nodeid[0]
test_tables = TablesTestTetra3D(float_precision, d_cell_loctoglob, g_cell_nodeid)
test_tables.init()

checker = TetraChecker3D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
checker.test_cell_info()
checker.test_face_info()
checker.test_node_info()
checker.test_halo_info()
checker.summary()


NameError: name 'domain_tables' is not defined

In [4]:
a = domain_tables.d_face_halofid[0]
print(a[0:100])

[ 5  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10
  0  0  0  0  0  0 12  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0 19  0]


In [12]:
ghostnid = test_tables.l_cell_ghostnid[2]
ghostnid = ghostnid[0:ghostnid[-1]]
a = test_tables.ghost_info[ghostnid][:, 0:4]


print(a)

[[ 0.25   5.125  0.375 -1.   ]
 [ 0.25   4.875 -0.375 -1.   ]
 [-0.25   4.875  0.375 -1.   ]
 [ 0.5    4.75  -0.375 -1.   ]
 [-0.25   4.625  0.75  -1.   ]
 [ 0.75   5.125  0.75  -1.   ]
 [ 0.25   4.375 -0.375 -1.   ]
 [-0.25   4.375  0.375 -1.   ]
 [ 0.5    4.25  -0.375 -1.   ]
 [-0.25   4.125  0.75  -1.   ]
 [ 0.25   5.125  1.875 -1.   ]
 [-0.25   4.875  1.875 -1.   ]
 [-0.25   4.625  2.25  -1.   ]
 [-0.25   4.375  1.875 -1.   ]
 [ 1.25   4.875 -0.375 -1.   ]
 [ 1.5    4.75  -0.375 -1.   ]
 [ 1.25   4.375 -0.375 -1.   ]]


In [55]:
a = unified_domain.d_node_ghostid[0]


print(a[0].shape)

(7,)


In [67]:
b = test_tables.g_cell_nodeid[0]
print(b)
c = test_tables.g_node_cellid[b[0:b[-1]]]
print(c)
a = test_tables.l_node_cellid[0]

print(a)

[ 4 53 71 52  4]
[[  0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   1]
 [  0   1   3 600  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   4]
 [  0   1   2   3   4  60  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   6]
 [  0   1   2   6  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   4]]
[[  0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   1]
 [  0   1   3 600  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   4]
 [  0   1   2   3   4  60  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1   6]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1]]


In [60]:
test_tables.g_node_cellid[0].shape

(25,)

In [46]:
module = importlib.import_module("helpers.TetraChecker3D")
importlib.reload(module)
TetraChecker3D = getattr(module, "TetraChecker3D")

checker = TetraChecker3D(decimal_precision=4, domain_tables=domain_tables, unified_domain=unified_domain, test_tables=test_tables)
# checker.test_cell_info()
checker.test_face_info()
# checker.test_node_info()
# checker.test_halo_info()
checker.summary()

[3 6 1 0] [3 3 1 0] [[1 3 1]
 [3 1 1]
 [1 1 1]
 [1 1 3]]
====
[3 6 1 0] [3 3 1 0] [[0.33333333 5.         0.5       ]
 [0.33333333 4.83333333 0.        ]
 [0.         4.83333333 0.5       ]
 [0.33333333 4.83333333 0.5       ]]
[0 5 0 0] [0 3 0 0] [[0 1 1]
 [1 3 1]
 [0 3 1]
 [0 3 1]]
====
[0 5 0 0] [0 3 0 0] [[ 0.33333333  4.66666667 14.5       ]
 [ 0.33333333  4.83333333 15.        ]
 [ 0.66666667  4.83333333 14.5       ]
 [ 0.66666667  4.66666667 14.5       ]]
[0 0 6 0] [0 0 4 0] [[0 4 2]
 [0 2 2]
 [2 2 4]
 [0 4 2]]
====
[0 0 6 0] [0 0 4 0] [[9.33333333 0.33333333 0.5       ]
 [9.66666667 0.33333333 0.5       ]
 [9.66666667 0.16666667 0.        ]
 [9.33333333 0.16666667 0.5       ]]
[4 0 2 5] [4 0 2 4] [[2 2 4]
 [2 2 4]
 [2 2 2]
 [4 2 2]]
====
[4 0 2 5] [4 0 2 4] [[ 9.66666667  0.         14.5       ]
 [ 9.66666667  0.16666667 14.5       ]
 [10.          0.16666667 14.5       ]
 [ 9.66666667  0.16666667 15.        ]]

# ============================== #
# ========== Summary ===========

False

In [37]:
a = test_tables.g_face_name[0:100]
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [6 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 5]

In [10]:
a = test_tables.g_face_cellid[:, :, 1] == -1
b = test_tables.face_center[a]

a1 = b[:, 0] <= 0.01 #1
a2 = b[:, 0] >= 9.99 #2
a3 = b[:, 1] <= 0.01 #4
a4 = b[:, 1] >= 4.99 #3
a5 = b[:, 2] <= 0.01 #6
a6 = b[:, 2] >= 14.99 #5

print(b[a1].shape)
print(b[a2].shape)
print(b[a3].shape)
print(b[a4].shape)
print(b[a5].shape)
print(b[a6].shape)
print(b.shape)

(200, 3)
(200, 3)
(200, 3)
(200, 3)
(200, 3)
(200, 3)
(1200, 3)


In [22]:
a = unified_domain.d_face_oldname[0]

a1 = unified_domain.d_face_center[0][a == 1]
a2 = unified_domain.d_face_center[0][a == 2]
a3 = unified_domain.d_face_center[0][a == 3]
a4 = unified_domain.d_face_center[0][a == 4]
a5 = unified_domain.d_face_center[0][a == 5]
a6 = unified_domain.d_face_center[0][a == 6]
#print(a)
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)
print(a6.shape)

(200, 3)
(200, 3)
(202, 3)
(202, 3)
(198, 3)
(198, 3)


In [41]:
print(unified_domain.d_face_center[0][a == 4])

[[ 9.66666667  0.16666667 15.        ]
 [ 0.33333333  0.          0.5       ]
 [ 9.66666667  0.16666667  0.        ]
 [ 9.66666667  0.         14.5       ]
 [ 0.33333333  0.          2.        ]
 [ 0.66666667  0.          1.        ]
 [ 1.33333333  0.          0.5       ]
 [ 0.33333333  0.          3.5       ]
 [ 0.66666667  0.          2.5       ]
 [ 0.33333333  0.          5.        ]
 [ 0.66666667  0.          4.        ]
 [ 0.33333333  0.          6.5       ]
 [ 0.66666667  0.          5.5       ]
 [ 0.33333333  0.          8.        ]
 [ 0.66666667  0.          7.        ]
 [ 0.33333333  0.          9.5       ]
 [ 0.66666667  0.          8.5       ]
 [ 0.33333333  0.         11.        ]
 [ 0.66666667  0.         10.        ]
 [ 0.33333333  0.         12.5       ]
 [ 0.66666667  0.         11.5       ]
 [ 0.66666667  0.         14.5       ]
 [ 0.33333333  0.         14.        ]
 [ 0.66666667  0.         13.        ]
 [ 2.33333333  0.          0.5       ]
 [ 1.66666667  0.        

In [43]:
b = unified_domain.d_faces[0][a == 4]
b[0]

print(unified_domain.d_node_name[0][b[0][0:b[0][-1]]])

[4 2 2]


In [15]:
p = 0
d_cells = domain_tables.d_cells[p]
d_nodes = domain_tables.d_nodes[p][:, 0:3]
d_faces = domain_tables.d_faces[p][:, 0:3] #square
d_cell_faces = domain_tables.d_cell_faces[p]
i = 0
c_faces = d_cell_faces[i][0:d_cell_faces[i][-1]]
c_faces_nodes = d_faces[c_faces]
c_nodes = d_cells[i][0:d_cells[i][-1]]

faces_node = np.array([
  c_nodes[[0, 1, 2]],
  c_nodes[[0, 1, 3]],
  c_nodes[[0, 2, 3]],
  c_nodes[[1, 2, 3]]
], dtype=np.int32)



tmp_faces_node = np.sort(faces_node, axis=1)
tmp_c_faces_nodes = np.sort(c_faces_nodes, axis=1)
print(tmp_faces_node)
print(tmp_c_faces_nodes)

matches = np.all(tmp_faces_node == tmp_c_faces_nodes[:, np.newaxis, :], axis=2)
sorted_indexes = np.argmax(matches, axis=0)



[[  6  62 106]
 [  6  61  62]
 [  6  61 106]
 [ 61  62 106]]
[[  6  62 106]
 [  6  61 106]
 [  6  61  62]
 [ 61  62 106]]


In [35]:
a = domain_tables.d_cell_ghostnid[0]

print(a.shape)

(1463, 18)


In [45]:
domain_tables.d_cell_cellfid[0].shape

(6000, 5)

In [ ]:
i = 0
triangle_nf1 = domain_tables.d_cell_cellfid[0]
arr = np.arange(0, len(domain_tables.d_cell_cellfid[0]))

filter = triangle_nf1[:, -1] == 4


a = triangle_nf1[filter] - arr[filter, np.newaxis]
a = a[:, 0:4]
#a = np.abs(a)
#a = np.sort(a, axis=1)
# a = np.array([row[np.argsort(np.abs(row))] for row in a])
print(np.unique(a.flatten()))


In [ ]:
triangle_nf1 = unified_domain.d_cell_cellfid[0]
arr = np.arange(0, len(unified_domain.d_cell_cellfid[0]))

filter = triangle_nf1[:, -1] == 6



a = triangle_nf1[filter] - arr[filter, np.newaxis]
a = a[:, 0:6]
a = np.array([row[np.argsort(np.abs(row))] for row in a])
print(np.unique(a, axis=0))


In [ ]:
sorted_rows = np.array([row[np.argsort(np.abs(row))] for row in arr])

In [8]:
import numpy as np
np.ndarray(shape=(1), dtype=np.int32)

array([0], dtype=int32)

In [ ]:
# Backup

def general(self, g_cell_nodeid, nb_nodes, max_face_nodeid, max_cell_faceid, dim):
  """
  create:
    g_node_cellid
    g_cell_cellnid
    g_face_nodeid
    g_cell_faceid
    g_face_cellid
    g_cell_cellfid
    nb_faces
  """

  def _is_in_array(array: 'int[:]', item: 'int') -> 'int':
    """
      Check if an item is in the array
      Return 1 if the item is in the array otherwise 0

      Note:
        The number of item in the array must be array[-1]
    """
    for i in range(array[-1]):
      if item == array[i]:
        return 1
    return 0

  def count_max_node_cellid(cells: 'int[:, :]', nb_nodes: 'int'):
    """
      Determine the max neighboring cells of a node across all cells
    """
    res = np.zeros(shape=(nb_nodes), dtype=np.int32)
    for cell in cells:
      for i in range(cell[-1]):
        node = cell[i]
        res[node] += 1
    return np.max(res)

  def count_max_cell_cellnid(
          cells: 'int[:, :]',
          node_cellid: 'int[:, :]',
  ):
    """
      Get the maximum number of neighboring cells per cell's nodes across the mesh

      Details:
      For each cell in the mesh, we need to examine its nodes and count the cells that neighbor those nodes.
      to get all neighboring cells of the cell
      Then, determine the highest number of neighboring cells

      Args:
        cells: (cell_id => nodes of the cell)
        node_cellid: (node_id => neighboring cells of the node)

      Return:
        Maximum number of neighboring cells per cell's nodes across the mesh

      Implementation details:
        to ensure that a neighboring cell is visited only once, we set `visited[neighbor_cell] = cell_id`
        thus for the same neighboring cell `visited[neighbor_cell]` is already set by `cell_id`
        for the next cell `visited` will automatically reset because next_cell_id != all_old_cell_id
    """
    visited = np.zeros(cells.shape[0], dtype=np.int32)

    max_counter = 0
    for i in range(cells.shape[0]):
      counter = 0
      for j in range(cells[i][-1]):
        node_n = node_cellid[cells[i][j]]
        for k in range(node_n[-1]):
          if node_n[k] != i and visited[node_n[k]] != i:
            visited[node_n[k]] = i
            counter += 1
      max_counter = max(max_counter, counter)
    return max_counter

  def create_node_cellid(cells: 'int[:, :]', node_cellid: 'int[:, :]'):
    """
      Create neighboring cells for each node
    """
    for i in range(cells.shape[0]):
      for j in range(cells[i][-1]):
        node = node_cellid[cells[i][j]]
        size = node[-1]
        node[-1] += 1
        node[size] = i

  def create_cell_cellnid(
          cells: 'int[:, :]',
          node_cellid: 'int[:, :]',
          cell_cellnid: 'int[:, :]',
  ):
    """
      Get all neighboring cells by collecting adjacent cells from each node of the cell.
    """
    for i in range(cells.shape[0]):
      for j in range(cells[i][-1]):
        node_n = node_cellid[cells[i][j]]
        for k in range(node_n[-1]):
          if node_n[k] != i and _is_in_array(cell_cellnid[i], node_n[k]) == 0:
            size = cell_cellnid[i][-1]
            cell_cellnid[i][-1] += 1
            cell_cellnid[i][size] = node_n[k]

  # ###############
  # Create_info
  # ###############

  def _has_the_same_items(arr1: 'int[:]', arr2: 'int[:]', size: 'int'):
    """
      Check if all items of arr1 are in arr2

      Note:
        Not fast for large arrays
    """
    for i in range(size):
      found = 0
      for j in range(size):
        if arr1[j] == arr2[i]:
          found = 1
          break
      if found == 0:
        return 0
    return 1

  def _has_face(cell_faces: 'int[:]', face: 'int[:]', face_size: 'int', faces: 'int[:, :]'):
    """
      Check if `face` is in `cell_faces`

      Args:
        cell_faces: cell => cell's face ids
        face: face's node ids
        face_size: number of nodes of the face.
        faces: face_id => nodes of the face.

      Complexity: n_cellf * n_facen ^ 2

      Return:
        The face id if it exist in `cell_faces` otherwise -1

    """
    for i in range(cell_faces[-1]):
      face_nodes = faces[cell_faces[i]]
      if face_size == face_nodes[-1] and _has_the_same_items(face_nodes, face, face_size):
        return cell_faces[i]
    return -1

  def _intersect_nodes(face_nodes: 'int[:]', nb_nodes: 'int', node_cellid: 'int[:, :]',
                       intersect_cell: 'int[:]'):
    """
      Get the common cells of neighboring cells of the face's nodes.

      Details:
      Identify the neighboring cells associated with each of the nodes that belong to a specific face.
      After identifying the neighboring cells for each of these nodes, we are interested in finding the common cells that are shared among all these neighboring cells.

      Args:
        face_nodes: nodes of the face
        nb_nodes : number of nodes of the face
        node_cellid: for each node get the neighbor cells

      Return:
        intersect_cell: array(2) common cells between all neighbors of each node (two at most)
    """
    index = 0

    intersect_cell[0] = -1
    intersect_cell[1] = -1

    cells = node_cellid[face_nodes[0]]
    for i in range(cells[-1]):
      intersect_cell[index] = cells[i]
      for j in range(1, nb_nodes):
        if _is_in_array(node_cellid[face_nodes[j]], cells[i]) == 0:
          intersect_cell[index] = -1
          break
      if intersect_cell[index] != -1:
        index = index + 1
      if index >= 2:
        return

  def _create_faces(nodes: 'int[:]', out_faces: 'int[:, :]', size_info: 'int[:]', cell_type: 'int'):
    """
      Create cell faces

      Args:
        nodes : nodes of the cell
        cell_type :
          5 => triangle
          6 => rectangle
          7 => tetrahedron
          9 => hexahedron
          8 => pyramid

      Return:
        out_faces: faces of the cell
        size_info:
          size_info[:-1] contains number of nodes of each face
          size_info[-1] total number of faces of the cell

      Notes:
      'tet': {'tri': [[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]]},

      'hex': {'quad': [[0, 1, 2, 3], [0, 1, 4, 5], [1, 2, 5, 6],
                       [2, 3, 6, 7], [0, 3, 4, 7], [4, 5, 6, 7]]},

      'pyr': {'quad': [[0, 1, 2, 3]],
              'tri': [[0, 1, 4], [1, 2, 4], [2, 3, 4], [0, 3, 4]]}

    """
    triangle = 5
    rectangle = 6
    tetrahedron = 7
    hexahedron = 8
    pyramid = 9

    if cell_type == triangle:
      out_faces[0][0] = nodes[0]
      out_faces[0][1] = nodes[1]
      size_info[0] = 2  # number of nodes

      out_faces[1][0] = nodes[1]
      out_faces[1][1] = nodes[2]
      size_info[1] = 2

      out_faces[2][0] = nodes[2]
      out_faces[2][1] = nodes[0]
      size_info[2] = 2

      size_info[-1] = 3  # number of faces
    elif cell_type == rectangle:
      out_faces[0][0] = nodes[0]
      out_faces[0][1] = nodes[1]
      size_info[0] = 2  # number of nodes

      out_faces[1][0] = nodes[1]
      out_faces[1][1] = nodes[2]
      size_info[1] = 2

      out_faces[2][0] = nodes[2]
      out_faces[2][1] = nodes[3]
      size_info[2] = 2

      out_faces[3][0] = nodes[3]
      out_faces[3][1] = nodes[0]
      size_info[3] = 2

      size_info[-1] = 4  # number of faces
    elif cell_type == tetrahedron:
      out_faces[0][0] = nodes[0]
      out_faces[0][1] = nodes[1]
      out_faces[0][2] = nodes[2]
      size_info[0] = 3  # number of nodes

      out_faces[1][0] = nodes[0]
      out_faces[1][1] = nodes[1]
      out_faces[1][2] = nodes[3]
      size_info[1] = 3

      out_faces[2][0] = nodes[0]
      out_faces[2][1] = nodes[2]
      out_faces[2][2] = nodes[3]
      size_info[2] = 3

      out_faces[3][0] = nodes[1]
      out_faces[3][1] = nodes[2]
      out_faces[3][2] = nodes[3]
      size_info[3] = 3

      size_info[-1] = 4  # number of faces
    elif cell_type == hexahedron:
      out_faces[0][0] = nodes[0]
      out_faces[0][1] = nodes[1]
      out_faces[0][2] = nodes[2]
      out_faces[0][3] = nodes[3]
      size_info[0] = 4

      out_faces[1][0] = nodes[0]
      out_faces[1][1] = nodes[1]
      out_faces[1][2] = nodes[4]
      out_faces[1][3] = nodes[5]
      size_info[1] = 4

      out_faces[2][0] = nodes[1]
      out_faces[2][1] = nodes[2]
      out_faces[2][2] = nodes[5]
      out_faces[2][3] = nodes[6]
      size_info[2] = 4

      out_faces[3][0] = nodes[2]
      out_faces[3][1] = nodes[3]
      out_faces[3][2] = nodes[6]
      out_faces[3][3] = nodes[7]
      size_info[3] = 4

      out_faces[4][0] = nodes[0]
      out_faces[4][1] = nodes[3]
      out_faces[4][2] = nodes[4]
      out_faces[4][3] = nodes[7]
      size_info[4] = 4

      out_faces[5][0] = nodes[4]
      out_faces[5][1] = nodes[5]
      out_faces[5][2] = nodes[6]
      out_faces[5][3] = nodes[7]
      size_info[5] = 4

      size_info[-1] = 6
    elif cell_type == pyramid:
      out_faces[0][0] = nodes[0]
      out_faces[0][1] = nodes[1]
      out_faces[0][2] = nodes[2]
      out_faces[0][3] = nodes[3]
      size_info[0] = 4

      out_faces[1][0] = nodes[0]
      out_faces[1][1] = nodes[1]
      out_faces[1][2] = nodes[4]
      size_info[1] = 3

      out_faces[2][0] = nodes[1]
      out_faces[2][1] = nodes[2]
      out_faces[2][2] = nodes[4]
      size_info[2] = 3

      out_faces[3][0] = nodes[2]
      out_faces[3][1] = nodes[3]
      out_faces[3][2] = nodes[4]
      size_info[3] = 3

      out_faces[4][0] = nodes[0]
      out_faces[4][1] = nodes[3]
      out_faces[4][2] = nodes[4]
      size_info[4] = 3

      size_info[-1] = 5
    else:
      raise Exception('Unknown cell type')


  def create_info(
    cells: 'int[:, :]',
    node_cellid: 'int[:, :]',
    faces: 'int[:, :]',
    cell_faces: 'int[:, :]',
    face_cellid: 'int[:, :]',
    cell_cellfid: 'int[:, :]',
    faces_counter: 'int[:]',
    max_nb_nodes: 'int',
    max_nb_faces: 'int',
    dim: 'int',
  ):
    """
      - Create faces
      - Create cells with their corresponding faces (cells.cellfid).
      - Create neighboring cells for each face (faces.cellid).
      - Create neighboring cells of a cell by face (cells.cellid).

      Args:
        cells: cells with their nodes (cell => cell nodes)
        node_cellid: neighbor cells of each node (node => neighbor cells)
        max_nb_nodes : maximum number of nodes on faces
        max_nb_faces : maximum number of faces on cells

      Return:
        faces : (face => face nodes)
        cell_faces : (cell => cell faces)
        face_cellid : (face => neighboring cells of the face)
        faces_counter : array(1) face counter
        cell_cellfid : (cell => neighboring cells of a cell by face)

    """

    tmp_cell_faces = np.zeros(shape=(max_nb_faces, max_nb_nodes), dtype=np.int32)
    tmp_size_info = np.zeros(shape=(max_nb_faces + 1), dtype=np.int32)
    intersect_cells = np.zeros(2, dtype=np.int32)

    for i in range(cells.shape[0]):
      cell_type = cells[i][-1] + dim
      _create_faces(cells[i], tmp_cell_faces, tmp_size_info, cell_type)

      # For every face of the cell[i]
      # Get the intersection of the neighboring cells of this face's nodes
      # The result should be two cells `intersect_cells`
      for j in range(tmp_size_info[-1]):
        _intersect_nodes(tmp_cell_faces[j], tmp_size_info[j], node_cellid, intersect_cells)

        # check if the face already created
        face_id = _has_face(cell_faces[i], tmp_cell_faces[j], tmp_size_info[j], faces)

        # Create face if not exist
        if face_id == -1:
          face_id = faces_counter[0]
          faces_counter[0] += 1
          # copy nodes from tmp_cell_faces
          for k in range(tmp_size_info[j]):
            faces[face_id][k] = tmp_cell_faces[j][k]
          faces[face_id][-1] = tmp_size_info[j]

        # Create cells with their corresponding faces.
        # The face has at most two neighbors
        # Assign the face to both of them
        the_cell = cell_faces[intersect_cells[0]]
        if _is_in_array(the_cell, face_id) == 0:
          the_cell[the_cell[-1]] = face_id
          the_cell[-1] += 1
        if intersect_cells[1] != -1 and _is_in_array(cell_faces[intersect_cells[1]], face_id) == 0:
          the_cell = cell_faces[intersect_cells[1]]
          the_cell[the_cell[-1]] = face_id
          the_cell[-1] += 1

        # Create neighboring cells of each face
        face_cellid[face_id][0] = intersect_cells[0]
        face_cellid[face_id][1] = intersect_cells[1]

        # Create neighboring cells of the cell by face
        tmp = cell_cellfid[i]
        if intersect_cells[0] == i and intersect_cells[1] != -1:
          tmp[tmp[-1]] = intersect_cells[1]
          tmp[-1] += 1
        elif intersect_cells[1] == i and intersect_cells[0] != -1:
          tmp[tmp[-1]] = intersect_cells[0]
          tmp[-1] += 1

  # ###############
  # End Create_info
  # ###############

  nb_cells = len(g_cell_nodeid)

  # create_node_cellid
  max_node_cellid = count_max_node_cellid(g_cell_nodeid, nb_nodes)
  node_cellid = np.ones(shape=(nb_nodes, max_node_cellid + 1), dtype=np.int32) * -1
  node_cellid[:, -1] = 0
  create_node_cellid(g_cell_nodeid, node_cellid)

  # create_cell_cellnid
  max_cell_cellnid = count_max_cell_cellnid(g_cell_nodeid, node_cellid)
  cell_cellnid = np.ones(shape=(nb_cells, max_cell_cellnid + 1), dtype=np.int32) * -1
  cell_cellnid[:, -1] = 0
  create_cell_cellnid(g_cell_nodeid, node_cellid, cell_cellnid)

  # create_info
  apprx_nb_faces = nb_cells * max_cell_faceid
  faces = np.ones(shape=(apprx_nb_faces, max_face_nodeid + 1), dtype=np.int32) * -1
  faces[:, -1] = 0
  cell_faceid = np.ones(shape=(nb_cells, max_cell_faceid + 1), dtype=np.int32) * -1
  cell_faceid[:, -1] = 0
  face_cellid = np.ones(shape=(apprx_nb_faces, 2), dtype=np.int32) * -1
  cell_cellfid = np.ones(shape=(nb_cells, max_cell_faceid + 1), dtype=np.int32) * -1
  cell_cellfid[:, -1] = 0
  face_counter = np.zeros(shape=(1), dtype=np.int32)
  create_info(g_cell_nodeid, node_cellid, faces, cell_faceid, face_cellid, cell_cellfid, face_counter, max_face_nodeid, max_cell_faceid, dim)
  faces = faces[:face_counter[0]]
  face_cellid = face_cellid[:face_counter[0]]

  def _sort_cell_faces(c_nodes, c_faces_nodes):
    faces_node = np.array([
      c_nodes[[0, 1, 2]],
      c_nodes[[0, 1, 3]],
      c_nodes[[0, 2, 3]],
      c_nodes[[1, 2, 3]]
    ], dtype=np.int32)

    tmp_faces_node = np.sort(faces_node, axis=1)
    tmp_c_faces_nodes = np.sort(c_faces_nodes, axis=1)

    matches = np.all(tmp_faces_node == tmp_c_faces_nodes[:, np.newaxis, :], axis=2)
    sorted_indexes = np.argmax(matches, axis=0)

    return faces_node, sorted_indexes

  for i in range(len(cell_faceid)):
    a = cell_faceid[i]


  self.g_node_cellid = node_cellid
  self.g_cell_cellnid = cell_cellnid
  self.g_face_nodeid = faces
  self.g_cell_faceid = cell_faceid
  self.g_face_cellid = face_cellid[cell_faceid[:, 0:-1]]
  self.g_cell_cellfid = cell_cellfid
  self.nb_faces = face_counter[0]


In [5]:
    def create_info(
      cells: 'int[:, :]',
      node_cellid: 'int[:, :]',
      faces: 'int[:, :]',
      cell_faces: 'int[:, :]',
      face_cellid: 'int[:, :]',
      cell_cellfid: 'int[:, :]',
      faces_counter: 'int[:]',
      tmp_cell_faces: 'int[:, :, :]',
      tmp_size_info: 'int[:, :]',
      dim: 'int',
    ):
      """
        - Create faces
        - Create cells with their corresponding faces (cells.cellfid).
        - Create neighboring cells for each face (faces.cellid).
        - Create neighboring cells of a cell by face (cells.cellid).

        Args:
          cells: cells with their nodes (cell => cell nodes)
          node_cellid: neighbor cells of each node (node => neighbor cells)
          max_nb_nodes : maximum number of nodes on faces
          max_nb_faces : maximum number of faces on cells

        Return:
          faces : (face => face nodes)
          cell_faces : (cell => cell faces)
          face_cellid : (face => neighboring cells of the face)
          faces_counter : array(1) face counter
          cell_cellfid : (cell => neighboring cells of a cell by face)

      """

      intersect_cells = np.zeros(2, dtype=np.int32)
      _create_cell_faces_n(cells, tmp_cell_faces, tmp_size_info, dim)

      for i in range(cells.shape[0]):
        # For every face of the cell[i]
        # Get the intersection of the neighboring cells of this face's nodes (N*n*n)
        # The result should be two cells `intersect_cells`
        for j in range(tmp_size_info[i, -1]):
          _intersect_nodes(tmp_cell_faces[i, j], tmp_size_info[i, j], node_cellid, intersect_cells)
          # The face has at most two neighbors
          # swap to make intersect_cells[0] = cell_i id
          if intersect_cells[1] == i:
            intersect_cells[1] = intersect_cells[0]
            intersect_cells[0] = i

          # Check if the face is already created
          face_id = cell_faces[i]
          # Create face if not exist
          if face_id == -1:
            face_id = faces_counter[0]
            faces_counter[0] += 1
            # copy nodes from tmp_cell_faces
            for k in range(tmp_size_info[j]):
              faces[face_id][k] = tmp_cell_faces[j][k]
            faces[face_id][-1] = tmp_size_info[j]

          # (cell_faces) Create cell faces.
          cell_faces[i, j] = face_id
          sc = intersect_cells[1] # second cell
          if sc != -1:
            k = _get_face_index(tmp_cell_faces[sc], tmp_size_info[sc], faces[face_id])
            cell_faces[sc, k] = face_id

          # (face_cellid) Create neighboring cells of each face
          face_cellid[face_id, 0] = intersect_cells[0]
          face_cellid[face_id, 1] = intersect_cells[1]

          # (cell_cellfid) Create neighboring cells of the cell by face
          cell_cellfid[i, j] = intersect_cells[1]

(1331, 25)