In [1]:
import os
import numpy as np

dim = 3
float_precision = 'float32'
root_file = os.getcwd()
mesh_path = 'tetrahedron.msh'
mesh_path = os.path.join(root_file, 'mesh', mesh_path)

def get_members(a):
  return [m for m in dir(a) if not m.startswith("__")]


In [5]:
import os
import numpy as np

dim = 3
float_precision = 'float32'
root_file = os.getcwd()
mesh_path = 'tetrahedron.msh'
mesh_path = os.path.join(root_file, 'mesh', mesh_path)

def get_members(a):
  return [m for m in dir(a) if not m.startswith("__")]

import importlib

module_1 = importlib.import_module("create_domain_utils")
importlib.reload(module_1)
module = importlib.import_module("create_domain")
importlib.reload(module)
Mesh = getattr(module, "Mesh")
Domain = getattr(module, "Domain")
LocalDomain = getattr(module, "LocalDomain")

mesh = Mesh(mesh_path, dim)
domain = Domain(mesh, float_precision)
print(domain.cells.shape[0])


local_domains_data = domain.c_create_sub_domains(4)
# new_nb_part = len(local_domains_data)

# PC
# 2m 2s -> 30000 (nid)
# 37s -> 4 (nid)
# c 10s -> 4 (fid)
# c 40s -> 30000 (fid)
# c 1m 42s -> 30000 (nid)
# ---- laptop
# 1m 44s -> 4 (nid)
# print(local_domains_data)


gmsh:physical => triangle
gmsh:physical => tetra
[1 1 1 ... 6 6 6]
{'gmsh:physical': {'triangle': array([1, 1, 1, ..., 6, 6, 6]), 'tetra': array([1, 1, 1, ..., 1, 1, 1])}}


NotImplementedError: 

In [3]:
print(local_domains_data[0].nodes.shape[0])

76


In [2]:
from manapy.partitions import MeshPartition
from manapy.base.base import Struct

running_conf = Struct(backend="numba", signature=True, cache=True, float_precision=float_precision)
a = MeshPartition(mesh_path, dim=dim, conf=running_conf, periodic=[0,0,0])

# 6m 49 -> 30000
# 2m -> 3000
# 28s -> 4
# ----
# 1m 26s -> 4


Reading gmsh file ...

Mesh partitionning ...
Elapsed time: 38.457 s
Elapsed time: 71.264 s


In [125]:
for i in range(domain.cells.shape[0]):
  c = domain.cells[i]
  if 110 in c and 363 in c:
    print(i, c)

5697 [ 362 1294  110  363    4]
5698 [1294  597  110  363    4]
5699 [110 597 111 363   4]


In [116]:
domain.node_phyfaceid[111]

array([ 608,  609,  610, 1189, 1190, 1191,    6], dtype=int32)

In [119]:
c = 5699
print(domain.cells[c])
r = domain.cell_faceid[5699]
print(r)
print(domain.faces[r[0:-1]])

[110 597 111 363   4]
[11987 11986 11988 11989     4]
[[110 597 111   3]
 [597 110 363   3]
 [110 111 363   3]
 [597 111 363   3]]


In [96]:
a = domain.node_phyfaceid
print(a[0:100])

[[ 399  799  980  981    0    0    4]
 [ 380  381  580  581  780  781    6]
 [ 400  600 1180 1181    0    0    4]
 [ 180  181  218  219  800    0    5]
 [   0  200  599    0    0    0    3]
 [ 199  818  819 1018 1019    0    5]
 [ 618  619  999 1199    0    0    4]
 [  18   19  418  419 1000    0    5]
 [ 219  238  239  800  801  820    6]
 [ 239  258  259  820  821  840    6]
 [ 259  278  279  840  841  860    6]
 [ 279  298  299  860  861  880    6]
 [ 299  318  319  880  881  900    6]
 [ 319  338  339  900  901  920    6]
 [ 339  358  359  920  921  940    6]
 [ 359  378  379  940  941  960    6]
 [ 379  398  399  960  961  980    6]
 [ 779  798  799  981  982  983    6]
 [ 759  778  779  983  984  985    6]
 [ 739  758  759  985  986  987    6]
 [ 719  738  739  987  988  989    6]
 [ 699  718  719  989  990  991    6]
 [ 679  698  699  991  992  993    6]
 [ 659  678  679  993  994  995    6]
 [ 639  658  659  995  996  997    6]
 [ 619  638  639  997  998  999    6]
 [ 979  998 

In [155]:
a = domain.face_name
print(len(a[a == 2]))

0


In [49]:
for item in domain.phy_faces:
  a = item[0:item[-1]-1]
  a = np.sort(a)
  #print(a)
  if np.all(a == np.array([100, 101])):
    print(item)

[100 101 296   3]
[100 101 377   3]


In [32]:
for p in range(4):
  a = local_domains[p].map_nodes.get(110)
  print(a)

None
None
None
383


In [23]:
c = 0
for p in range(4):
  a = local_domains[p].map_phy_faces.values()
  a = np.array(list(a))
  a.sort()
  #print(a)
  print(len(a))
  c += len(a)
print(c)



351
254
243
350
1198


In [4]:
a = {}
a[0] = len(a)
print(a)

{0: 0}


In [4]:
import importlib

module = importlib.import_module("create_domain")
importlib.reload(module)
Domain = getattr(module, "Domain")

domain = Domain(mesh_path, dim, float_precision)
print(domain.cells.shape)


Init
triangle
tetra
_create_cells
node_cellid
cell_cellnid
_create_info
Warning create_cell_info_3d is not implemented
Execution time: 0.004878 seconds
(6000, 5)


In [5]:
print(domain.cell_cellfid)

[[  -1   -1   -1    1    1]
 [   0    3   -1    2    3]
 [   1    6   -1    4    3]
 ...
 [5995 5993   -1 5998    3]
 [5996   -1 5997 5999    3]
 [  -1 5998   -1   -1    1]]


In [3]:
# 511104 -> 1.3s
# 5821794 -> 17.9s
members = [m for m in dir(domain.meshio_mesh) if not m.startswith("__")]
print(members)

print(domain.meshio_mesh.cell_data)

['cell_data', 'cells', 'element_sets', 'field_data', 'gmsh_periodic', 'info', 'node_sets', 'point_data', 'points', 'prune', 'read', 'write']
{'triangle': {'gmsh:physical': array([1, 1, 1, ..., 4, 4, 4])}, 'tetra': {'gmsh:physical': array([66, 66, 66, ..., 66, 66, 66])}}


In [12]:
print(domain.meshio_mesh.cell_data['tetra']['gmsh:physical'])

[66 66 66 ... 66 66 66]


In [4]:
from manapy.partitions import MeshPartition
from manapy.base.base import Struct
from manapy.ddm import Domain

def create_partitions(mesh_file_path, float_precision, dim):
  running_conf = Struct(backend="numba", signature=True, cache=True, float_precision=float_precision)
  MeshPartition(mesh_file_path, dim=dim, conf=running_conf, periodic=[0,0,0])
  domain = Domain(dim=dim, conf=running_conf)
  return domain

domain = create_partitions(mesh_path, float_precision, dim)

Reading gmsh file ...

Saving partition files ...
Number of Cells: 6000
Number of Vertices: 1331
Local domain contruction ...
Start ...
Execution time: 0.046104 seconds


In [8]:
domain.faces.nodeid.shape[0]

12600

In [26]:
domain.meshio_mesh.cell_data['tetra']['gmsh:physical'][0::10]

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66