In [5]:
import meshio
import os
import numpy as np

PATH = os.getcwd()
PATH = os.path.join(PATH, 'mesh', 'tetrahedron.msh')
meshio_mesh = meshio.read(PATH)
MESHIO_VERSION = int(meshio.__version__.split(".")[0])
if MESHIO_VERSION < 4:
  meshio_mesh_cells = meshio_mesh.cells
else:
  meshio_mesh_cells = meshio_mesh.cells_dict

print(meshio_mesh_cells.keys())
m_triangles = meshio_mesh_cells['tetra']
m_points = meshio_mesh.points

print(m_triangles)

dict_keys(['triangle', 'tetra'])
[[  4  53  71  52]
 [ 53  71  52 358]
 [ 52 358  71 116]
 ...
 [367 520 115  25]
 [520  26 115  25]
 [115  26   6  25]]


In [10]:
arr = [1, 2, 3, 4]
a = np.ones(shape=(14), dtype=np.int64)

a[0:4] = arr
print(a)

[1 2 3 4 1 1 1 1 1 1 1 1 1 1]


In [ ]:
g_cell_nodeid = m_triangles
nb_nodes = len(m_points)
max_face_nodeid = 3
max_cell_faceid = 4
dim = 3

nb_cells = len(g_cell_nodeid)

# create_node_cellid
max_node_cellid = count_max_node_cellid(g_cell_nodeid, nb_nodes)
node_cellid = np.ones(shape=(nb_nodes, max_node_cellid + 1), dtype=np.int32) * -1
node_cellid[:, -1] = 0
create_node_cellid(g_cell_nodeid, node_cellid)

# create_cell_cellnid
max_cell_cellnid = count_max_cell_cellnid(g_cell_nodeid, node_cellid)
cell_cellnid = np.ones(shape=(nb_cells, max_cell_cellnid + 1), dtype=np.int32) * -1
cell_cellnid[:, -1] = 0
create_cell_cellnid(g_cell_nodeid, node_cellid, cell_cellnid)

# create_info
tmp_cell_faces = np.zeros(shape=(nb_cells, max_cell_faceid, max_face_nodeid), dtype=np.int32)
tmp_size_info = np.zeros(shape=(nb_cells, max_cell_faceid + 1), dtype=np.int32)
tmp_cell_faces_map = np.zeros(shape=(nb_cells, max_cell_faceid * 2 + 1), dtype=np.int32)

apprx_nb_faces = nb_cells * max_cell_faceid
faces = np.ones(shape=(apprx_nb_faces, max_face_nodeid + 1), dtype=np.int32) * -1
faces[:, -1] = 0
cell_faceid = np.ones(shape=(nb_cells, max_cell_faceid + 1), dtype=np.int32) * -1
cell_faceid[:, -1] = 0
face_cellid = np.ones(shape=(apprx_nb_faces, 2), dtype=np.int32) * -1
cell_cellfid = np.ones(shape=(nb_cells, max_cell_faceid + 1), dtype=np.int32) * -1
cell_cellfid[:, -1] = 0
face_counter = np.zeros(shape=(1), dtype=np.int32)
create_info(g_cell_nodeid, node_cellid, faces, cell_faceid, face_cellid, cell_cellfid,
            face_counter, tmp_cell_faces, tmp_size_info, tmp_cell_faces_map, dim)
faces = faces[:face_counter[0]]
face_cellid = face_cellid[:face_counter[0]]

g_node_cellid = node_cellid
g_cell_cellnid = cell_cellnid
g_face_nodeid = faces
g_cell_faceid = cell_faceid
g_face_cellid = face_cellid[cell_faceid[:, 0:-1]]
g_cell_cellfid = cell_cellfid
nb_faces = face_counter[0]

In [1]:
class Test:
  def __init__(self, a, b):
    self.a, self.b = a, b


a = Test(1, 2)
print(a.a, a.b)

1 2
